// src/lib/sections/Landing.svelte
<script>
  // For parallax scrolling effect
  let scrollY

  // Featured image path based on theme
  $: featuredImagePath = '/nice_photos/Copy of 6S1A2936.jpg'
</script>

<svelte:window bind:scrollY />

<div class="relative min-h-screen" id="home">
  <!-- Parallax Hero Background -->
  <div class="absolute inset-0 h-full w-full overflow-hidden">
    <img
      src={featuredImagePath}
      alt="HackHarvard"
      class="absolute h-full w-full object-cover object-center"
    />
    <div class="absolute inset-0 bg-black bg-opacity-50" />
  </div>

  <!-- Hero Content -->
  <div
    class="relative flex min-h-screen flex-col items-center px-4 py-16 text-white sm:px-6 sm:py-24"
  >
    <div class="mx-auto max-w-6xl text-center">
      <h1
        class="font-lexend mt-10 sm:mt-20 mb-4 text-5xl font-bold tracking-tighter drop-shadow-lg sm:mb-6 sm:text-6xl md:text-7xl lg:text-8xl"
      >
        HackHarvard
      </h1>

      <p
        class="font-exo mb-4 text-sm font-normal text-gray-300 drop-shadow-sm sm:mb-6 sm:text-base md:text-lg lg:text-xl"
      >
        Hosted by HackHarvard Undergraduate Hackathon
      </p>

      <h2
        class="font-exo mb-8 text-xl font-semibold drop-shadow-md sm:mb-12 sm:text-2xl md:text-3xl lg:text-4xl"
      >
        October 3-5, 2025 · Cambridge, MA
      </h2>

      <!-- Early Application Notice -->
      <div class="mb-8 rounded-lg bg-white bg-opacity-20 p-4 backdrop-blur-sm sm:mb-12 sm:p-6">
        <p class="font-exo text-base font-medium text-white drop-shadow-sm sm:text-lg md:text-xl">
          🚀 <strong>Applications are now closed.</strong> Thank you to everyone who applied — we hope you had a great time at the event.
        </p>
      </div>

      <!-- Photo Accent Bar - responsive for mobile -->
      <div class="my-8 flex flex-wrap justify-center gap-4 sm:my-12 sm:flex-nowrap sm:space-x-6">
        <div
          class="h-32 w-32 transform overflow-hidden rounded-full border-4 border-white shadow-lg transition-transform hover:scale-105 sm:h-40 sm:w-40 md:h-52 md:w-52 lg:h-64 lg:w-64"
        >
          <img
            src="/nice_photos/Copy of 6S1A2293.jpg"
            alt="HackHarvard event"
            class="h-full w-full object-cover"
          />
        </div>
        <div
          class="h-32 w-32 transform overflow-hidden rounded-full border-4 border-white shadow-lg transition-transform hover:scale-105 sm:h-40 sm:w-40 md:h-52 md:w-52 lg:h-64 lg:w-64"
        >
          <img
            src="/nice_photos/Copy of 6S1A2875.jpg"
            alt="HackHarvard event"
            class="h-full w-full object-cover"
          />
        </div>
        <div
          class="h-32 w-32 transform overflow-hidden rounded-full border-4 border-white shadow-lg transition-transform hover:scale-105 sm:h-40 sm:w-40 md:h-52 md:w-52 lg:h-64 lg:w-64"
        >
          <img
            src="/nice_photos/Copy of 6S1A2655.jpg"
            alt="HackHarvard event"
            class="h-full w-full object-cover"
          />
        </div>
      </div>

      <div class="gap-4 sm:flex-col">
        <div class="mt-6 flex flex-col flex-wrap justify-center gap-4 sm:mt-8 sm:flex-row sm:gap-6">
          <a
            href="/what"
            target="_blank"
            class="transform rounded-lg bg-white px-5 py-3 text-base font-bold text-black shadow-xl transition-all hover:-translate-y-1 hover:bg-opacity-90 sm:text-lg"
          >
            What is a hackathon?
          </a>

          <a
            href="#welcome"
            class="transform rounded-lg border-2 border-white bg-transparent px-5 py-3 text-base font-bold shadow-xl transition-all hover:-translate-y-1 hover:bg-white hover:bg-opacity-20 sm:text-lg"
          >
            Learn More
          </a>
        </div>
      </div>
    </div>
  </div>

</div>

<style>
  /* Custom styles */
  :global(html) {
    scroll-behavior: smooth;
  }
</style>

// src/lib/sections/Landing.jsx
import React from 'react'
import { Link } from 'react-router-dom'

const featuredImagePath = '/nice_photos/Copy of 6S1A2936.jpg'

export default function Landing() {
  return (
    <div className="relative min-h-screen" id="home">
      <div className="absolute inset-0 h-full w-full overflow-hidden">
        <img
          src={featuredImagePath}
          alt="HackHarvard"
          className="absolute h-full w-full object-cover object-center"
        />
        <div className="absolute inset-0 bg-black bg-opacity-50" />
      </div>

      <div className="relative flex min-h-screen flex-col items-center px-4 py-16 text-white sm:px-6 sm:py-24">
        <div className="mx-auto max-w-6xl text-center">
          <h1 className="mb-4 mt-10 font-lexend text-5xl font-bold tracking-tighter drop-shadow-lg sm:mb-6 sm:mt-20 sm:text-6xl md:text-7xl lg:text-8xl">
            HackHarvard
          </h1>

          <p className="mb-4 font-exo text-sm font-normal text-gray-300 drop-shadow-sm sm:mb-6 sm:text-base md:text-lg lg:text-xl">
            Hosted by HackHarvard Undergraduate Hackathon
          </p>

          <h2 className="mb-8 font-exo text-xl font-semibold drop-shadow-md sm:mb-12 sm:text-2xl md:text-3xl lg:text-4xl">
            October 3-5, 2025 · Cambridge, MA
          </h2>

          <div className="mb-8 rounded-lg bg-white bg-opacity-20 p-4 backdrop-blur-sm sm:mb-12 sm:p-6">
            <p className="font-exo text-base font-medium text-white drop-shadow-sm sm:text-lg md:text-xl">
              🚀 <strong>Applications are now closed.</strong> Thank you to everyone who applied —
              we hope you had a great time at the event.
            </p>
          </div>

          <div className="my-8 flex flex-wrap justify-center gap-4 sm:my-12 sm:flex-nowrap sm:space-x-6">
            <div className="h-32 w-32 transform overflow-hidden rounded-full border-4 border-white shadow-lg transition-transform hover:scale-105 sm:h-40 sm:w-40 md:h-52 md:w-52 lg:h-64 lg:w-64">
              <img
                src="/nice_photos/Copy of 6S1A2293.jpg"
                alt="HackHarvard event"
                className="h-full w-full object-cover"
              />
            </div>
            <div className="h-32 w-32 transform overflow-hidden rounded-full border-4 border-white shadow-lg transition-transform hover:scale-105 sm:h-40 sm:w-40 md:h-52 md:w-52 lg:h-64 lg:w-64">
              <img
                src="/nice_photos/Copy of 6S1A2875.jpg"
                alt="HackHarvard event"
                className="h-full w-full object-cover"
              />
            </div>
            <div className="h-32 w-32 transform overflow-hidden rounded-full border-4 border-white shadow-lg transition-transform hover:scale-105 sm:h-40 sm:w-40 md:h-52 md:w-52 lg:h-64 lg:w-64">
              <img
                src="/nice_photos/Copy of 6S1A2655.jpg"
                alt="HackHarvard event"
                className="h-full w-full object-cover"
              />
            </div>
          </div>

          <div className="gap-4 sm:flex-col">
            <div className="mt-6 flex flex-col flex-wrap justify-center gap-4 sm:mt-8 sm:flex-row sm:gap-6">
              <Link
                to="/what"
                className="transform rounded-lg bg-white px-5 py-3 text-base font-bold text-black shadow-xl transition-all hover:-translate-y-1 hover:bg-opacity-90 sm:text-lg"
              >
                What is a hackathon?
              </Link>

              <a
                href="#welcome"
                className="transform rounded-lg border-2 border-white bg-transparent px-5 py-3 text-base font-bold shadow-xl transition-all hover:-translate-y-1 hover:bg-white hover:bg-opacity-20 sm:text-lg"
              >
                Learn More
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
